apiVersion: v1
kind: Namespace
metadata:
  name: acm-sample-policy
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST-CSF
  name: acm-sample-policy
  namespace: acm-sample-policy
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: acm-sample-policy-limitrange
      spec:
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - acm-*
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: LimitRange
            metadata:
              name: acm-sample-limitrange
            spec:
              limits:
              - default:
                  memory: 256Mi
                defaultRequest:
                  memory: 128Mi
                type: Container
        remediationAction: inform
        severity: medium
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: acm-sample-policy-namespace
      spec:
        namespaceSelector:
          exclude:
          - kube-*
          include:
          - default
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: acm-policy-namespace
        remediationAction: inform
        severity: low
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-acm-sample-policy
  namespace: acm-sample-policy
placementRef:
  name: k8s-staging
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: acm-sample-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: k8s-staging
  namespace: acm-sample-policy
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - "k8s-staging"
