apiVersion: v1                    
kind: Namespace
metadata:
  name: acm-sample-app
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: acm-sample-app
  namespace: acm-sample-app
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: 
      - acm-sample-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-sample-app
  namespace: acm-sample-app
spec:
  type: Git
  pathname: 'https://github.com/iconeb/acm-example.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: sample-app
  labels:
    app: acm-sample-app
  name: acm-sample-app
  namespace: acm-sample-app
spec:
  channel: acm-sample-app/acm-sample-app
  placement:
    placementRef:
      kind: PlacementRule
      name: stage-prod
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: acm-sample-app
  name: stage-prod
  namespace: acm-sample-app
spec:
  clusterSelector:
    matchLabels:
      'stage': 'prod'
